config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # get 'home', to: 'pages#home', as: 'home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
    member do
      get :follow
      get :unfollow
      get :favs
    end
    resources :tweets, only: [:index, :create]
  end

  resources :tweets, only: [] do
    member do
      get :like
    end
  end

  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:index, :create]
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_latest-sidebar.html.erb
<div class="sidebarcontainer">

  <div class="whotofollow">
    <div class="wtftitle">
      <h5>Who to follow</h5>
    </div>
    <% User.all.sample(5).each do |usr|  %>
      <div class="wtfusers">
        <div class="wtf-avatar" style="
        padding-right: 14px;">
          <i class="fas fa-user-circle"></i>
        </div>
        <div class="wtf-userdata">
          <div class="wtf-userdata-usrname"> <%= usr.username  %></div>
          <div class="wtf-userdata-usrhandle">@<%= usr.handle  %></div>
        </div>
        <div class="wtf-follow">
          <% @user = usr %>
          <div class="usr-follow-btn" data-controller="followings">
            <% if current_user.id != @user.id %>
              <% if !current_user.following?(@user) %>
                <%= link_to follow_user_path(@user) do %>
                  <follow class="wtf-fllwbtn follow">Follow</follow>
                <% end  %>
              <% else  %>
                <%= link_to unfollow_user_path(@user) do %>
                  <follow class="wtf-fllwbtn following" data-action="mouseover->followings#over mouseout->followings#out">Following</follow>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end  %>

  </div>

</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag ("logo_baptiste.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <!-- <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li> -->
          <li class="nav-item dropdown">
            <%= link_to "@#{current_user.handle}", "#", class: "nav-handle dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <!-- <%= link_to "Login", new_user_session_path, class: "nav-link" %> -->
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_user-sidebar.html.erb
<div class="sidebarcontainer">

  <div class="sbflexbox">

    <div class="sbactions">
      <%= link_to root_path, :class => 'home_links' do %>
        <i class="fas fa-home"></i>
        <sbacttext> Home  </sbacttext>
      <% end %>
    </div>
    <div class="sbactions">
      <%= link_to conversations_path, :class => 'home_links' do %>
        <i class="fas fa-envelope"></i>
        <sbacttext>Messages</sbacttext>
      <% end %>
    </div>
    <div class="sbactions">
      <%= link_to favs_user_path(@user), :class => 'home_links' do %>
        <i class="fas fa-bookmark" style="padding-left: 3px;"></i>
        <sbacttext>Bookmarks</sbacttext>
      <% end %>
    </div>
    <div class="sbactions">
      <%= link_to user_path(@user), :class => 'home_links' do %>
      <i class="fas fa-user" style="padding-left: 3px;"></i>
      <sbacttext>Profile</sbacttext>
      <% end %>
    </div>
  </div>



</div>